name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests in Chrome (Headless)
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress Videos (On Failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Cypress Screenshots (On Failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload HTML Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-reports
          path: cypress/reports/
